name: rsgx

on:
  push:
    branches: [ 'rsgx**' ]
  pull_request:
    branches: [ 'rsgx**' ]

jobs:
  test:

    runs-on: ubuntu-18.04
    container: 
      image: baiduxlab/sgx-rust:1804-1.1.1

    steps:
    - uses: actions/checkout@v2
    - name: cat 
      run: cat /root/.bashrc
    - name: add cargo to system path
      run: echo "::add-path::/root/.cargo/bin"
    - name: cargo
      run: cargo --version
    - name: Build
      run: source /root/.bashrc && cargo build --verbose
      shell: bash
    - name: Run tests
      run: cd tests/sgx && cmake .. && make test-sgx
      shell: bash
